### PR TITLE
implemented media-player and media-source

### PR DESCRIPTION
**Pull request by ryachen01**

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
Ok, I think this new interface makes sense, now we need to update all the datasets... Hopefully it's a purely mechanical update we can script.

**Comment by gcampax** [comment]
I think there is an issue with linting of dataset.tt files that go across skills. Anyway we're still missing all the updates to paraphrase.tsv and annotated.txt everywhere. Let me know when you want me to look at this again.

**Comment by ryachen01** [comment]
@gcampax How can I fix the scenario tests?

**Comment by gcampax** [comment]
Looks like one of the scenario files is now malformed? Maybe an A turn wraps incorrectly?

**Comment by gcampax** [comment]
Alright, tests pass, let's merge this so we can work to enable media players for Home Assistant as well.

**Pull request merged**
