### PR TITLE
Fix owlbot with missing definitions

### LINKED ISSUE #277: Bad error message for missing definitions in Owlbot
Currently, if Owlbot doesn't know a word, the agent replies with "Request failed with status code 404", which is not nice. We should catch that error and show a more informative error message.

### PR DESCRIPTION
**Pull request by gcampax**
Fixes #277

### CODE REVIEW

**Review by AydanPirani — APPROVED** [review]

**Comment by AydanPirani** [comment]
@gcampax  LGTM! Just one quick question: the wording in the scenario test deviates from that within manifest by an extra "sorry", is this fine?

**Comment by gcampax** [comment]
Not only it is fine, it must be that way! The skill-independent templates in Genie automatically add "Sorry" in front of error messages, so you need to include that in the scenario test, because that's what the agent actually says.

**Comment by AydanPirani** [comment]
Oh okay, makes sense! I think we're good to go :)

**Comment by gcampax** [comment]
It's good to go when tests pass. Tests don't pass yet...

**Pull request merged**
