### PR TITLE
Wip/new spotify

### PR DESCRIPTION
**Pull request by ryachen01**
Updated dev set

@AydanPirani

### CODE REVIEW

**Comment by gcampax** [comment]
I have to check this carefully with a sample of representative examples, but the best way to do a basic check for this is to run the typecheck once we have the new manifest
(`make datadir/fewshot` is a quick way to force a typecheck over the dev set and manually annotated training set)

**Comment by AydanPirani** [comment]
@gcampax  Code throws this error:

`Error: Syntax error in manifest.tt line 55: Parse error: unexpected token extends in state 112, expected #[,#_[,%,&&,),*,**,+,,,-,.,/,:,;,<=,=,==,=>,=~,>=,TYPE_ANNOT,],as,asc,desc,filter,of,||,},~=`

**Comment by gcampax** [comment]
Ok, after merging and reinstalling deps I don't get the same error. `make datadir/fewshot` fails for a different reason though:
"play the album magic mystery tour" is misannotated as:
```
now => ((@com.spotify.playable()), album == null^^com.spotify:album("magic mystery tour")) => @com.spotify.play(song=id);
```

@ryachen01 did you reannotate "play album" commands?

**Comment by ryachen01** [comment]
@gcampax @AydanPirani 

"play the album magic mystery tour" was part of the training set, which I haven't reannotated yet. I believe Aydan made a series of changes to both the train and dev sets, and they're inconsistent with the annotations I made earlier. Just so we're all on the same page, the following annotations represent the basic logic I've been following. Are they correct?

- Play "X" 
    -  now => (@com.spotify.playable() filter id =~ "X")[1] => @com.spotify.play(playable=id);
- Play the song "X" 
    -  now => (@com.spotify.song() filter id =~ "X")[1] => @com.spotify.play(playable=id);
- Play the album "X" 
    -  now => com.spotify.song() filter album == null^^com.spotify:album("X") => @com.spotify.play(playable=id);

**Comment by gcampax** [comment]
I think the last one will be:
```
@com.spotify.album() filter id =~ "X" => @com.spotify.play(playable=id);
```

We should adopt the convention of using `@com.spotify.song()` if either one of the following is true:
- the sentence uses the words "song", "track", or other non-ambiguous keywords
- the sentence uses any song-specific filters (ie, genre, energy, danceability)

**Comment by gcampax** [comment]
And to clarify, we will use the same logic to annotate as album (either unambiguously using the word "album" or using album-specific parameters, which currently are none). The rest should be playable.

**Comment by gcampax** [comment]
Ok @AydanPirani @ryachen01,
I did a pass over manifest and dataset. With the fixes, and with https://github.com/stanford-oval/genie-toolkit/pull/441, I can generate a good synthetic training set that matches the aforementioned annotation convention.
Let's finish fixing the dev set and manually annotated set (ie, fix until `make datadir/fewshot` passes) and we should be good to train the first model on the newly refactored skill, to see how well we're doing.
For reference, the current skill is about 70-71% accurate on the snips NLU benchmark, and I expect a 5-10% boost in accuracy from this refactoring. Maybe more!

**Comment by ryachen01** [comment]
`make datadir/fewshot` should pass now

**Comment by gcampax** [comment]
Ok, it didn't run for me right away but it does now. I'm going to start training a model to see how well this work does. Meanwhile either of you can start on the new implementation, and shortly after updating the unit tests and scenario tests?

**Comment by gcampax** [comment]
I think there is still an issue in the dev set by the way: sentences of the form "Play the best music from Klaus Badelt ." are tagged with `@com.spotify.song` instead of `@com.spotify.playable`. This doesn't match the training set, which uses playable for the word "music".

**Comment by gcampax** [comment]
So, I ran some training overnight. Unfortunately the results are rather disappointing: while I no longer see any confusion between song and album (yay!), the overall accuracy only increases by 0.6% on Spotify. Basically, with the new model we gain a lot of sentences, but we also lose a lot of sentences that the old model was parsing correctly.
(Don't be disheartened: that's the way of research! Sometimes you win, and sometimes you fight the machine and the machine wins. If you always know what you're doing, it's too easy and not research)

It seems "genre" is now causing issues that it was not causing before, and I suspect it's because genre is in the song table, not in the playable table. @ryachen01 is there a reason for this? I see in the implementation genre is a property of artists anyway, we can attach it to albums as well. I'm going to try and see if that improves as well.

In any case, I uploaded the detailed error analysis at https://crowdie.stanford.edu/~gcampagn/spotify/83-fixed.nlu.debug if you want to peruse it and spot some class of error that we can fix. And I put the list of all models on my tracking spreadsheet at https://docs.google.com/spreadsheets/d/159oZV2aE4Jy7lTzyweSIuy03tU4rh1HPPIr8M8A63wo/edit#gid=1370732290

In any case, @Mehrad0711 it looks like you are in luck: there is no easy solution to Spotify, and we'll need high quality NED to get through this. So if you can do a run on 83 that would be very helpful. Note that we now have a "playable" type that is a superclass of both "song" and "album". That shouldn't affect you too much though, you can probably still write "song | album" as the entity type.

**Comment by ryachen01** [comment]
The reason we don’t have genres as a property of album is because the Spotify search api doesn’t allow you to search albums by genre. I think we can still extract genre as a property. The problem this causes is that queries such as “play a

**Comment by gcampax** [comment]
If the issue is searching by album, if the user asks "find a pop album", we can search for pop songs and then find the albums associated with each song, and I think that will be good enough. The hardest problem is getting the natural language parser to work - everything we can hack in how we call the API, we'll take it.

**Comment by gcampax** [comment]
Alright, after cleaning up genre too, we get a 4% boost in Spotify accuracy, up to 77.3% on the whole dev set. This is a pretty good result, I think we should be very happy with it. Now let's get it over the line by finishing the implementation :)

**Comment by gcampax** [comment]
I think this looks good, can you update the unit tests and scenario tests as well?

**Comment by ryachen01** [comment]
Yeah I can do that

**Comment by gcampax** [comment]
Do a merge of the master branch as well before you start, it will help.

**Comment by gcampax** [comment]
Alright, looks like things are mostly in order, thank you for working on this!
It looks like we need https://github.com/stanford-oval/genie-toolkit/pull/454 to pass tests.
I'm going to wait until Travis finishes, merge that one, upgrade the genie dependency here, and then merge everything. Hopefully Travis will pass quickly.

**Review by gcampax — APPROVED** [review]

**Pull request merged**
