### PR TITLE
Remove duplicate songs

### PR DESCRIPTION
**Pull request by ryachen01**
Resolves Issue #236

### CODE REVIEW

**Review by gcampax — APPROVED** [review]
Ah, it looks like this existed already, but was not used for playable. That makes sense.

Nice, thanks!

**Comment by gcampax** [comment]
Looks like you need to update the tests as well.

**Comment by ryachen01** [comment]
How do I trigger the tests again?

**Comment by gcampax** [comment]
I think you need to push something to the branch associated with the PR to trigger the test. Any commit should do.

**Comment by gcampax** [comment]
Alright, let's merge this!

**Pull request merged**
