### PR TITLE
Spotfiy Bug Fixes 

### PR DESCRIPTION
**Pull request by ryachen01**
The entityMatchScore in the Spotify skill should be consistent with https://github.com/stanford-oval/genie-toolkit/blob/13ff4e5cc8fe56422ce35c7d37846062eb12377d/lib/dialogue-agent/entity-linking/entity-finder.js#L55

### CODE REVIEW

**Comment by ryachen01** [comment]
Bugs fixed by PR:

-  do_player_shuffle function wasn't working properly because we weren't passing in a device as a parameter 

- overlapping queues

    - Instead of adding songs to the queue we should just play the list of songs to prevent the queue from getting really long and messy

- When playing songs by artist, the order of songs returned was inconsistent with the order of songs being played.  

    - To fix this when we return the list of songs we have to sort by popularity then when playing the songs we first must turn shuffle to false then we can just play the artist with the context uri parameter

- Albums were also in the wrong order

    - When you search for songs in an album the search api returns them in order of popularity not in order of the album, so we have to call a different api endpoint to get the right order for an album.  https://github.com/stanford-oval/thingpedia-common-devices/blob/c0e4b4186a68a687d3383b5e162e4eb67b47126c/main/com.spotify/index.js#L352

**Comment by gcampax** [comment]
Is this still a draft or is it ready for review? Is it fixing any of the bugs reported by Monica?

**Comment by ryachen01** [comment]
Still a draft for now. There's a couple more bugs that this pr needs to fix.

**Comment by gcampax** [comment]
Can we split it into multiple PRs? We can review them piecemeal, and keep updating the Spotify skill, which helps people testing (especially Monica).

**Review by gcampax — APPROVED** [review]
Yeah looks good.

**Pull request merged**
